import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Generated by Next.js",
    template: "%s | Generated by Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={
          {
            display: "flex",
            justifyContent: "space-between",
            padding: "1rem",
            borderBottom: "1px solid #ccc",
          }
        }>
          <p>Header</p>
        </header>
        {children}
        <footer
        style={
          {
            display: "flex",
            justifyContent: "space-between",
            padding: "1rem",
            borderTop: "1px solid #ccc",
          }
        
        }>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  );
}
